import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Components from '@/components'
import { ColorModeScript } from "@chakra-ui/react";
import theme from '@/chakra'
const inter = Open_Sans({ 
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Dental Appointment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Components.ChakraUIProvider>
          {children}
        </Components.ChakraUIProvider>
      </body>
    </html>
  );
}
